#!/bin/bash

#########################################################
# CREADOR: Jose Luis Izquierdo Mañas
# Correo: joluizquierdo@correo.ugr.es
#########################################################

clean:
	rm -rfv *.class