#!/bin/bash

#########################################################
# CREADOR: Jose Luis Izquierdo Mañas
# Correo: joluizquierdo@correo.ugr.es
#########################################################

compile:
	javac Client_User.java


clean:
	rm -rfv *.class